### ISSUE TITLE
Transition background

### ISSUE THREAD

**Issue by git-hwa** [NewAmsterdamLabs/ZOZolaZoomTransition#5]
Really love this library and thank for making this awesome one.

I have a problem during integration of this library.
The problem is my main background color is black on all over the scenes, but during the transitioning from master view to detail view, the background is white and changes back to black.
How can I handle this background to make it black like my main background.

**Comment by scalessec** [comment]
The `ZOZolaZoomTransition` instance has a property named `fadeColor` that defaults to `[UIColor whiteColor]`. If you set this to `[UIColor blackColor]` the transition will fade through black instead of white.

**Comment by git-hwa** [comment]
@scalessec  Thank you!
