### ISSUE TITLE
zo_snapshot triggering UITableView reload 

### ISSUE THREAD

**Issue by taher-mosbah** [NewAmsterdamLabs/ZOZolaZoomTransition#7]
I'm trying to use ZOZolaZoomTransition with a tableView, both in simulator and device running iOS 10 when popping a view controller "zo_snapshot" triggers a UITableView reload which causes the tableView to scroll back to top (in my case), this is not the behaviour with the collectionView in the demo app. Is there any way to avoid this ? 
![screen_shot](https://cloud.githubusercontent.com/assets/2300087/18834587/0aead7ac-83f7-11e6-9875-4a1244a0d93c.png)

Thank you.

**Comment by scalessec** [comment]
Weird. But regardless, a `UITableView` reload shouldn't change the content offset of your table view. Are you sure you're not doing anything that would trigger that? I'm using this library all over the place in Objective-C and and Swift and haven't seen that behavior. Is this reproducible on iOS10 only?

**Comment by taher-mosbah** [comment]
Ah my bad, it was my code that causes the reload, I'm closing the issue, Thank you !
